### ISSUE TITLE
Nexilus GC Adapter not working

### ISSUE THREAD

**Issue by WinterAlexander** [libgdx/gdx-controllers#10] opened 2021-06-12 02:47 UTC
Exact model: https://www.amazon.ca/gp/product/B00S7CZWUQ/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1

Controller used with the adapter is an original GC controller.

Note that I have another controller (Logitech gamepad) with which I can confirm my game code works properly. The issues are only with this specific GC adapter.

Behavior with version 2.2.0
Windows: Controller is neither detected or startup nor when plugged in but plugging it in doesn't cause any slowdown
Linux: Controller is not detected but upon plugging it in the game takes ~100 ms to tick for every frame instead of the usual 1-2 ms. 

Another note is that there is a Wii U / PC switch on the device. All the tests were done in "PC" mode rather than Wii U mode as Wii U isn't detected as a controller on a PC. There is no slowdown on Linux in Wii U mode.

Behavior prior to version 2 (legacy gdx controllers) 
Windows and Linux works perfectly fine. The only difference is on windows it detects 4 controllers even if only one controller is plugged into the adapter while on Linux it detects 1 when 1 is plugged.

The adapter works great with Dolphin (Windows and Linux), mupen64plus with the SDL controller plugin (Linux), Project 64, etc.

If you want me to try the adapter on a specific SDL application, please send it to me so I can test. I'm pretty sure mupen uses SDL for controllers though but there is also a difference between SDL 1 and 2 which might come into play?

Other weird problem with the controller adapter: if I let it plugged in into my computer it cannot boot, the bios get stucks infinitely trying to figure out what this USB is. Happens on multiple computers with different motherboards. This is the only controller/adapter I own that does this.

**Comment by MrStahlfelge** [comment] 2021-06-12 08:44
Please read the notes concerning desktop in https://github.com/libgdx/gdx-controllers/wiki/Features

**Comment by WinterAlexander** [comment] 2021-06-12 15:16
The mapping tool works great with the controller, detecting it as 1 gamepad (tested on Linux)
![image](https://user-images.githubusercontent.com/8527540/121780633-4129d100-cb6f-11eb-819c-deb1384aca1a.png)
```
Searching gamepads...
Found 1 gamepad(s):
"NEXILUX GAMECUBE Controller Adapter", 03000000790000004518000010010000
Environment variable "SDL_GAMECONTROLLERCONFIG" is not defined
Checking if new mappings available from github: https://github.com/gabomdq/SDL_GameControllerDB
Mapping string: '03000000790000004518000010010000,NEXILUX GAMECUBE Controller Adapter,a:b1,b:b0,x:b2,y:b3,start:b9,rightshoulder:b7,dpup:h0.1,dpdown:b12,dpleft:h0.0,dpright:h0.2,leftx:b13,lefty:a1,rightx:a3,righty:a2,lefttrigger:b4,righttrigger:a4,platform:Linux,'
Searching gamepads...
Found 1 gamepad(s):
"NEXILUX GAMECUBE Controller Adapter", 03000000790000004518000010010000 (mapping available)
```

Thank you for the notes concerning desktop. I did not know about L2/R2. But this isn't much of a mapping problem as it is a simple controller getting detected and working problem? 

I tested the game on Linux. Works out of the box with the adapter with the mapping detected by the game/SDL DB! (No binding required from me)

No idea what could introduce the issue but it seems to not come from SDL. Maybe I should try on a libGDX game that uses gdx-controller 2.2.0? (Other than mine)

**Comment by WinterAlexander** [comment] 2021-06-12 16:35
I can confirm that the slowdown happens in `JamepadControllerMonitor#run`

This task takes on average 16 ms to run when the controller is plugged in but only about ~0.02 ms max when the controller is unplugged.

I can also confirm that in `jamepad/ControllerManager` there's never `nativeControllerConnectedOrDisconnected()` returning true  and benchmarking for `jamepad/ControllerManager#update` reveals that this native function call is not the source of the bottleneck.

Rather it's the "checkForNewControllers" that is costly:
```
Manager update 0.015965 ms
checkForNewControllers 13.252162 ms
Monitor update 0.010319 ms
```

I think the source of the bottleneck is from `jamepad/ControllerManager#nativeGetNumRollers()` which returns 0 but still takes time. Either `SDL_IsGameController(int)` struggles and gives up after a timeout or `SDL_NumJoysticks()` takes time? Would have to check the native code.

**Comment by MrStahlfelge** [comment] 2021-06-12 19:08
It still comes down to the mapping not being present in the mapping file, because I can't find "NEXILUX GAMECUBE Controller Adapter" in the mapping file this lib ships with. 

Where did you find the link to MrStahlfelge/Jamepad? It is an older version of https://github.com/libgdx/Jamepad and you'll find the SDL sources in the SDL repo linked there.

**Comment by WinterAlexander** [comment] 2021-06-12 20:03
Even if there is no mapping it should still work as a controller no? It seems to map to something though since it works out of the box on the SDL game and on the web version of your game. The SDL tool I tried has been compiled with SDL 2.0.7 so it might be a bug introduced in a newer version of SDL?

**Comment by MrStahlfelge** [comment] 2021-06-12 20:06
As stated in the Features section of this wiki:

> If a game controller can't get mapped, it won't show up.

That is this lib's behaviour, other SDL clients can handle this different. The fix is easy: Pull in a newer mapping db file.

**Comment by WinterAlexander** [comment] 2021-06-12 20:11
Thank you that makes sense. Will try adding another mapping file. Still I'm very curious where this behavior is programmed. Where is the native code that is commented out?

**Comment by MrStahlfelge** [comment] 2021-06-12 20:15
https://github.com/libgdx/Jamepad contains all the code used for desktop: Some Java code, some inline C code, and the SDL libs. I can't tell you where exactly the filtering happens, Jamepad was made by another author and I only added some new methods for new SDL features.

**Comment by WinterAlexander** [comment] 2021-06-12 20:20
I just don't find any C code in this repo though. I'm sorry I'm not familiar with JNI. Is the C code somehow generated from the java code comments?

IMO the best behavior to have when plugging in a controller with no mapping is to simply have the mappings unavailable but the controllers still usable just like they were in the legacy version of gdx-controllers. On top of that the slowdown is very weird.

**Comment by MrStahlfelge** [comment] 2021-06-12 20:36
Yes, jni-gen takes the C code from the comments.

I personally see much sense in having a controller added with unpredictable mapping, but this could be optional behaviour. Most people use an Xbox compatible controller anyway.

You are right, the slowdown shouldn't be. I don't know if this is caused by having an unmapped controller connected.

If you want to dive in, best is to clone Jamepad and see what the GitHub actions do to build the libs.

**Comment by WinterAlexander** [comment] 2021-06-12 21:08
As long as you have a menu to let the player bind their inputs it's valuable to support all controllers.

If the only code of Jamepad is the small bits I see in Java, I doubt rejecting the controller without mappings is a Jamepad behavior. Pretty sure it's an SDL behavior actually.

From what I see either `SDL_NumJoysticks()` returns 0 or `SDL_IsGameController` returns false, which are SDL functions. My guess is that `SDL_IsGameController` checks if the joystick is a game controller by checking the whole list of mappings. Doing this every frame takes a lot of time. I imagine it avoids checking the whole list when the controller is "open", leading it to only lag when the controller is "attempted to be checked" every frame.

This is purely an SDL behavior so I won't bother you with this anymore hahaha My controller works now thanks to my new mapping. Will likely try to fork Jamepad and this lib and try to make the whole thing support joysticks without bindings at some point. But I will first need to dabble in pure SDL to fully understand how it behaves.

**Comment by MrStahlfelge** [comment] 2021-06-12 21:27
The method is public and therefore should be cappable without problems from your desktop project.

If I remember correctly, SDL has the possibility to contruct new mappings if no mapping is present - I think that is the feature the game you tested uses which Jamepad does not use.

**Comment by WinterAlexander** [comment] 2021-06-12 21:51
The method is public but you can't get it's controllerManager object to call it on without reflection.

**Comment by MrStahlfelge** [comment] 2021-06-13 06:26
Ah, I see. You can try to override the file that it ships with by placing an own one in your resources, I am not sure if that works at the moment.
And I am open to accept PRs for an updated db file and changes so that the db file can get changed in projects. :-)

Thought about the problem with the fps as well. It could get easily fixed if new controllers wouldn't get checked that often. Connecting controllers to a machine is slow anyway, so it should be enough to check for a controllers only once a second or so.

**Comment by WinterAlexander** [comment] 2021-06-13 21:54
IMO, unless you have some sort of reason of not wanting the most up to date db file, the file should be downloaded from it's source repo by gradle on build rather than stored. I sure can open a PR though, will just need to make my windows bindings first.

From what I see in the SDL source code https://github.com/LuaDist/sdl/blob/master/src/joystick/SDL_gamecontroller.c it's indeed going through the entire database anytime one calls `SDL_IsGameController`. Jamepad could have some sort of cache remember which controllers GUID it queried and reset the cache only when the DB is modified to avoid querying the entire DB every frame. That being said I still have no idea why this is a Linux only problem.

**Comment by MrStahlfelge** [comment] 2021-06-21 21:13
> That being said I still have no idea why this is a Linux only problem.

The database file has different mappings for different operating systems. Sometimes on Windows it works because another mapping fits.

**Comment by WinterAlexander** [comment] 2021-06-21 21:42
But the controller was not detected on windows/not working, yet there was no slowdown.

**Comment by MrStahlfelge** [comment] 2021-06-21 22:33
Ah okay. For the slowdown see the open PR!

**Comment by MrStahlfelge** [comment] 2021-06-23 12:56
Okay, I am closing this now because the reason why the adapter is not shown is clear I think?

> IMO, unless you have some sort of reason of not wanting the most up to date db file, the file should be downloaded from it's source repo by gradle on build rather than stored. (It's currently behind by around 100 controllers).

Feel free to contribute a change doing so, but note that probably the 100 missing controllers are mostly the non-desktop ones I purged from the file to keep it small.

**Closed by MrStahlfelge** 2021-06-23 12:56 UTC
Labels: desktop
