### ISSUE TITLE
Issues with hotplugging on Desktop

### ISSUE THREAD

**Issue by Yontipon** [libgdx/gdx-controllers#29] opened 2023-03-10 23:06 UTC
### Summary

Due to using Jamepad's ControllerIndex object as the main way of tracking controllers on Desktop, Controller instances can change which physical controller they are paired with. This leads to misleading connect and disconnect events, and certain values being incorrect (maxButtonIndex) or unhelpful (uniqueId). Utilizing the SDL function SDL_JoystickGetDeviceInstanceID may be a potential solution.

### As an example to demonstrate the problem

_(Note: If on Windows, the controllers used in this example should be of the same type (XInput or DirectInput). See later section about why.)_

1. Connect physical controller A. gdx-controllers creates virtual controller A to take its input.
2. Connect physical controller B. gdx-controllers creates virtual controller B to take its input.
3. Disconnect physical controller A.

What happens next depends on the platform.

When testing on GWT, things work as I expect. Virtual controller A is reported as disconnected and removed from the list. Virtual controller B remains in the list, continues to take input from physical controller B, and all of its values remain unchanged.

When testing on Windows 7, virtual controller B is reported as disconnected and removed from the list instead. Virtual controller A now takes input from physical controller B. Its stored values (uniqueId, maxButtonIndex) are retained from virtual controller A, while values that are polled each time (controller name, playerIndex) become those of physical controller B.

_(Side note: When testing on Windows 10, both controllers are reported as disconnected, and a new virtual controller is created to take input from physical controller B. I don't know why this happens. It may be a separate issue, so I won't be addressing it here. In a way, this works around the issue I'm focusing on.)_

### Why does this happen?

The issues on Windows 7 seem to stem from using the Jamepad object ControllerIndex as the main way of tracking controllers. A ControllerIndex represents the controller at a fixed SDL index. When a controller disconnects, SDL moves the remaining controllers to fill the lowest index slots. gdx-controllers sees that the highest index slot has become empty and assumes the controller at that index was disconnected, when in reality, the highest index becomes empty regardless of which controller actually disconnects.

### What can be done?

In order to track controllers properly, we need a way to uniquely identify a physical controller from the time it is connected until it is disconnected. SDL provides a function that I believe provides such a value: SDL_JoystickGetDeviceInstanceID

https://wiki.libsdl.org/SDL2/SDL_JoystickGetDeviceInstanceID

The function is not currently exposed by libgdx/Jampad, but I believe it could be (sdl2gdx does so).

The gdx-controllers implementation on Android already seems to track controllers by the Android deviceId, so we would just be doing something similar on Desktop.

However, we still need the ControllerIndex objects, since we get our information about controllers from them. If we're trying to keep each Controller instance associated with the same physical controller for its lifetime, we'll actually need to shuffle the ControllerIndex objects between them when controllers are disconnected or connected.

### Additional note about Windows specifically

Jamepad lists the following under its Current Limitations section:

> "The order of gamepads on Windows is not necessarily the order they were plugged in. XInput controllers will always appear before DirectInput controllers, regardless of when they were plugged in. This means that the player numbers associated with each controller can change unexpectedly if XInput controllers are plugged in or disconnected while DirectInput controllers are present."

What this means for us is that we need to verify that each controller is with the correct ControllerIndex object not only when controllers are disconnected, but also when they are connected. 

Although the above note says that XInput controllers appear first, this seems to refer to the playerIndex value. In my testing, DirectInput controllers always take the lower SDL index number. Currently, connecting a DirectInput controller can cause it to "steal" an existing instance of Controller from an existing XInput controller. A new instance is then reported as connected, holding a controller that was already present. The DirectInput controller takes over the old controller's uniqueId and maxButtonIndex.

### Final comments

Let me know if my explanation wasn't clear enough or you have additional questions. It would be helpful if someone could test more platforms and operating systems (or verify my results). Do you agree with my understanding of the situation?

**Comment by MrStahlfelge** [comment] 2023-03-14 07:54
It is clear enough and I got it. I only had Windows 10 available to test and as you have seen, the problem is not really apparent on Windows 10 as it disconnects and reconnects completely. Also, I would suggest to test with the latest SDL version (2.26.4) and with `useRawInput = true`.

Feel free to make any changes that improve the situaion and open a PR.

**Comment by Yontipon** [comment] 2023-03-24 05:15
I want to be able to test changes to Jamepad, but I'm not sure how to do it. The BUILD file says that it can't be built locally on Windows, and must be cross-compiled. It looks like it's usually built as a Github action, but I wouldn't know how to make use of that in my fork. Do you have any advice for me? Do you have experience making changes to Jamepad on Windows?

**Comment by MrStahlfelge** [comment] 2023-03-26 13:45
You can simply fork and activate actions in your fork and the natives will be attached on the workflow run.

**Comment by Yontipon** [comment] 2023-04-08 20:47
I've got a set of changes just about ready, and I'm preparing to make my commit and pull request. I have changes to submit for both Jamepad and gdx-controllers, and the gdx-controllers changes depend on the Jamepad ones. Is there anything I should do to make it easier for testers to use them together? Changing version numbers or something?

**Comment by MrStahlfelge** [comment] 2023-04-09 07:31
Just submit the PR for jamepad first. When we reviewed and merged, you can depend on the latest jamepad snapshot for your gdc-controllers changes.

**Closed** 2023-04-27 08:00 UTC
